language: node_js
node_js:
    - 14

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false

deploy:
    provider: script
    script: npm run build
    skip_cleanup: true
    on:
        tags: true
        all_branches: false

